[package]
name = "cargo-show-asm"
version = "0.1.5"
edition = "2021"
description = "A cargo subcommand that displays the generated assembly of Rust source code."
categories = ["development-tools::cargo-plugins", "development-tools::debugging" ]
keywords = ["assembly", "plugins", "cargo"]
repository = "https://github.com/pacak/cargo-show-asm"
homepage = "https://github.com/pacak/cargo-show-asm"
authors = [ "Michael Baykov <manpacket@gmail.com>" ]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
bpaf = { version = "0.4.3", features = ["bpaf_derive"] }
cargo = "0.61"
glob = "0.3"
line-span = "0.1"
nom = "7.1"
once_cell = "1.9"
owo-colors = { version = "3.3.0", features = ["supports-colors"] }
regex = "1.5.4"
rustc-demangle = "0.1"
supports-color = "1.3"

[target.'cfg(target_family = "unix")'.dependencies]
nix = { version = "0.24.1", default-features = false, features = ["signal"] }

[[bin]]
name = "cargo-asm"
path = "src/main.rs"
