[package]
name = "cargo-show-asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
bpaf = { version = "0.3.2", path = "../bpaf", features = ["bpaf_derive"] }
atty = "0.2"
cargo = "0.60"
glob = "*"
once_cell = "*"
line-span = { git = "https://github.com/pacak/line-span", rev = "c4844e32f06b6d664327b55149f1b7df201bdc7f" }
nom = "*"
owo-colors = "3.2.0"
regex = "1.5.4"
rustc-demangle = "0.1"

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.23.0"

[[bin]]
name = "cargo-asm"
path = "src/main.rs"
