[package]
name = "cargo-show-asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bpaf = { version = "0.4.0", features = ["bpaf_derive"] }
atty = "0.2"
cargo = "0.61"
glob = "0.3"
once_cell = "1.9"
line-span = "0.1"
nom = "7.1"
owo-colors = "3.2.0"
regex = "1.5.4"
rustc-demangle = "0.1"

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.23.0"

[[bin]]
name = "cargo-asm"
path = "src/main.rs"
