on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt clippy

      - name: Tests
        run: cargo test --all-features

      - name: Clippy
        run: cargo clippy

      - name: Formatting
        run: cargo fmt --all check


