on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt clippy

      - name: Build allt the things
        run: cargo build --tests

      - name: Run unit tests
        run: cargo test --all-features

      - name: Clippy
        run: cargo clippy

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Native version works (Intel ASM)
        run: cargo run -- --manifest-path sample/Cargo.toml --intel sample::main

      - name: Native version works (LLVM)
        run: cargo run -- --manifest-path sample/Cargo.toml --llvm sample::main

      - name: Native version works (MIR)
        run: cargo run -- --manifest-path sample/Cargo.toml --mir sample::main
