on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt clippy
          targets: armv7-unknown-linux-gnueabihf

      - name: Build allt the things
        run: cargo build --tests

      - name: Run unit tests
        run: cargo test --all-features

      - name: Clippy
        run: cargo clippy

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Native version of cargo-show-asm (Intel ASM)
        run: >
          cargo clean --manifest-path sample/Cargo.toml &&
          cargo run -- --manifest-path sample/Cargo.toml --intel sample::main

      - name: Native version of cargo-show-asm (LLVM)
        run: >
          cargo clean --manifest-path sample/Cargo.toml &&
          cargo run -- --manifest-path sample/Cargo.toml --llvm sample::main

      - name: Native version of cargo-show-asm (MIR)
        run: >
          cargo clean --manifest-path sample/Cargo.toml &&
          cargo run -- --manifest-path sample/Cargo.toml --mir "main() -> ()"

          #      - name: Crosscompiled version of cargo-show-asm (Intel ASM)
          #        run: >
          #          cargo clean --manifest-path sample/Cargo.toml &&
          #          cargo run -- --manifest-path sample/Cargo.toml --intel sample::main --target armv7-unknown-linux-gnueabihf
